# Generated by Django 2.1 on 2019-02-09 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('name', models.CharField(max_length=50)),
                ('message_id', models.AutoField(primary_key=True, serialize=False)),
                ('bedrooms', models.IntegerField(blank=True, null=True)),
                ('square_feet', models.CharField(blank=True, max_length=20, null=True)),
                ('bathrooms', models.IntegerField(blank=True, null=True)),
                ('furniture', models.BooleanField(default=False)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('budget', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('message', models.TextField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
    ]
