# Generated by Django 2.1 on 2019-02-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0002_auto_20190209_2146'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='additional_message',
            field=models.TextField(blank=True, max_length=250, null=True),
        ),
    ]
