# Generated by Django 2.1.7 on 2019-04-14 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0004_booking_landmark'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=100)),
                ('property_rate', models.CharField(blank=True, max_length=20)),
                ('property_size', models.CharField(blank=True, max_length=20, null=True)),
                ('property_attributes', models.CharField(max_length=30)),
                ('property_description', models.TextField()),
                ('property_image1', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('property_image2', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('property_image3', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('property_image4', models.ImageField(blank=True, null=True, upload_to='uploads')),
                ('property_image5', models.ImageField(blank=True, null=True, upload_to='uploads')),
            ],
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='listing',
            name='property_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='realty.PropertyType'),
        ),
    ]
