# Generated by Django 2.1.7 on 2019-04-14 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0005_auto_20190414_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_thumbnail',
            field=models.ImageField(blank=True, upload_to='uploads'),
        ),
    ]
