# Generated by Django 2.1.7 on 2019-04-14 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0006_listing_property_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bathrooms',
        ),
        migrations.AddField(
            model_name='booking',
            name='property_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('house/villa', 'House/Villa'), ('plot', 'Plot')], default='apartment', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='purpose',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='property_bathrooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='property_intro',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='property_landmark',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='property_rooms',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='area',
            field=models.CharField(blank=True, choices=[('Bandra E', 'Bandra East'), ('Bandra W', 'Bandra West'), ('Khar E', 'Khar East'), ('Khar W', 'Khar West'), ('Santacruz E', 'Santacruz East'), ('Santacruz W', 'Santacruz West'), ('Parle E', 'Vile-Parle East'), ('Parle W', 'Vile-Parle West'), ('Andheri E', 'Andheri East'), ('Andheri W', 'Andheri West')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='furniture',
            field=models.CharField(choices=[('fully-furnished', 'Fully Furnished'), ('semi-furnished', 'Semi Furnished'), ('non-furnished', 'Non Furnished')], default='fully-furnished', max_length=20),
        ),
    ]
