# Generated by Django 2.1.7 on 2019-04-14 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0007_auto_20190414_1021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=20)),
                ('customer_phone', models.IntegerField(max_length=10)),
                ('customer_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('property_reference', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='realty.Listing')),
            ],
        ),
    ]
