# Generated by Django 2.2 on 2019-04-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('realty', '0009_auto_20190414_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='property_transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('rent', 'Rent'), ('sell', 'Sell')], default='buy', max_length=10),
        ),
    ]
